apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "go-template.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  - pods
  - secrets
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]