apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "go-template.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "go-template.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "go-template.fullname" . }}
  namespace: {{ .Release.Namespace }}