{{- if .Values.ingress.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata: 
  name: go-template-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.ingress.gateway.name }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.ingress.path }}
    route:
    - destination:
        host: {{ template "go-template.fullname" . }}
        port:
          number: {{ .Values.service.internalPort }}
{{- end }}